# Traefik v3.0 Configuration
# Production-ready configuration for HealthCare API

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry Points
entryPoints:
  # HTTP entry point (redirects to HTTPS)
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  
  # HTTPS entry point
  websecure:
    address: ":443"
    http:
      tls:
        options: default

# Providers
providers:
  # Docker provider
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-proxy
    watch: true

# Certificate Resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@domain.com  # CHANGE THIS
      storage: /acme.json
      keyType: EC256
      httpChallenge:
        entryPoint: web
      # Alternative: DNS challenge (uncomment if using)
      # dnsChallenge:
      #   provider: cloudflare
      #   delayBeforeCheck: 30s
      #   resolvers:
      #     - "1.1.1.1:53"
      #     - "8.8.8.8:53"

# TLS Configuration
tls:
  options:
    default:
      sslStrategies:
        - "tls.SniStrict"
      minVersion: "VersionTLS12"
      maxVersion: "VersionTLS13"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_RSA_WITH_AES_128_GCM_SHA256"

# API and Dashboard
api:
  dashboard: true
  debug: false
  insecure: false  # Dashboard only via HTTPS

# Logging
log:
  level: INFO
  format: json

# Access Logs
accessLog:
  format: json
  fields:
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep

# Metrics (Prometheus)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    manualRouting: false

# Health Check
ping:
  entryPoint: web

# Experimental Features
experimental:
  plugins:
    enabled: false